### ISSUE TITLE
Travis package installation 

### ISSUE THREAD

**Issue by scalingsolution** [PTScientists/MANIros#19]
I'm not quite sure how the travis setup works so far. I can find the script that starts the docker ros image but I am not sure how the other packages are included. For instance the adafruit module used for the servos.
Is the travis set-up somehow linked to the maniansible repo?

**Comment by mawalu** [comment]
Currently the ansible repo isn't used for the travis tests and only the dependencies installed in `ci/run.sh` are available. The adafruit module isn't installed because the current unit tests do not require it. In the future we want to run tests on real hardware which probably would require the entire environment defined in the ansible config.

**Comment by scalingsolution** [comment]
Ok thanks for the reply. That clears everything up.
